### ISSUE TITLE
Wmail doesn't always remember window position/state

### ISSUE THREAD

**Issue by Eldaw** [Thomas101/wmail#344]
Running v1.3.9 on Windows 10 x64.

I always use Wmail maximized on my primary monitor. Often when I launch Wmail, it hasn't remembered the window position and maximized state from the previous session. Instead, it opens as a small window in the middle of my primary monitor. See the attached screenshot. This means each time I need to maximize the window.

Other times, when it does remember its last window state, for the first second or two I see the outline of the small window in the middle, and then only after that does it take up the whole screen. So it's doing the window sizing in two different stages, which is a little jarring, and sometimes it seems it never gets to stage 2.

http://imgur.com/a/gQNju

**Comment by Thomas101** [comment]
Hmm that's odd. I'll take a look into this. Do you two monitors?

**Comment by Eldaw** [comment]
Yes, I use 2 monitors. Both running a resolution of 1920x1200.

**Comment by Thomas101** [comment]
Okay thanks for that. If you unplug one monitor, launch WMail and resize it, wait a minute or so for it to save to disk and then restart WMail does it remember the position then? I'm just wondering if it's to do with multiple displays

**Comment by Eldaw** [comment]
The same thing happens with just 1 monitor active so we can rule out 2 displays as being the cause.

It seems completely random as to whether it launches as a small window in the centre or whether it restores its maximized state. I've closed and re-opened it a few times in a row now, and sometimes it does one, and other times it does the other.

**Comment by Thomas101** [comment]
Fixed this in a616c39ab3d6e93cf8a55fb423799cfa348f012b. Thanks!

**Comment by Eldaw** [comment]
Still an issue with 2.0.4.

I quit v2.0.0, installed 2.0.4, and then launched the application, only to see a small window in the centre of my monitor instead of the expected maximized window.

**Comment by Thomas101** [comment]
I wonder if something was lost between the two versions. With your current install if you quit WMail and start it up again does it retain the state as you'd expect?

**Comment by Eldaw** [comment]
I've quit and restarted 2.0.4 a few times and each time the window starts maximized. I'll keep an eye on it. The issue as it exists now may well be restricted to after an upgrade is performed, changing from one version to another.

**Comment by Thomas101** [comment]
Okay thanks for checking that. If it does come up again don't hesitate to re-comment on this and I'll take another look.
