### ISSUE TITLE
After upgrading to 2.0.5, unread count in tray icon shows thousands  

### ISSUE THREAD

**Issue by amig** [Thomas101/wmail#421]
WMail v2.0.5
Ubuntu 16.04

After upgrading to version 2.0.5, the unread emails counter in the tray icon shows thousands of emails while there are only few.

I reinstall version 2.0.4 and things went back to normal.

**Comment by Thomas101** [comment]
Hi are you using a Gmail account or Google Inbox account? If you're using a Gmail account what type of inbox are you using (you can find out by going to setting in Gmail, then to the `inbox` tab and it's under `Inbox Type`). If you go to the settings in WMail, then the accounts tab, where it says `Unread Mode` which do you have selected?

**Comment by amig** [comment]
I'm using gmail/priority inbox.
In WMail I set it to 'Unread Important Messages'

**Comment by Thomas101** [comment]
There is an edge case in 2.0.5 that I know about where this can happen. I have fixed it, but it's not been released as yet. It would be good to check if this is the case though. If you go to View > Developer Tools and click the console tab. Paste the following...

```js
var mbx = window.remoteRequire('storage/mailboxStorage').allJSONItems()
Object.keys(mbx).forEach((k) => {
  if (k === '__index__') { return }
  var mb = mbx[k]
  console.log(JSON.stringify(mb.googleLabelInfo_v2))
})

var wvs = Array.from(document.querySelectorAll('webview'))
wvs.forEach((wv, ind) => {
  wv.addEventListener('ipc-message', (m) => {
    if (m.channel.type === 'tt') {
      console.log(ind, JSON.stringify(m.channel))
    }
  })
  wv.send('get-gmail-unread-count', {__respond__:'tt'})
})
```
You should get something like the following...
<img width="820" alt="screen shot 2016-11-06 at 10 39 59" src="https://cloud.githubusercontent.com/assets/103586/20036896/59eea3a2-a40d-11e6-9595-eece35e7cd07.png">

**Comment by Thomas101** [comment]
Hi, this has just been released in the 2.0.6 prerelease which you can download [here](https://thomas101.github.io/wmail/download?v=2.0.6). Thanks!

**Comment by amig** [comment]
Just updated to 2.0.6 and problem is still there. I've attached a screenshot that better describe the issue. It looks like it shows both important and total as one number instead of just showing the important unread emails.
![wmail-issue](https://cloud.githubusercontent.com/assets/203434/20132080/ded37210-a669-11e6-8004-6f8be981d1dd.png)

**Comment by amig** [comment]
I ran the above code in the console and got the following:
![screenshot from 2016-11-09 10-50-13](https://cloud.githubusercontent.com/assets/203434/20132182/622b5be6-a66a-11e6-89c7-765df6dfe78f.png)

**Comment by locly** [comment]
I've not seen (11 : 20) unread count in the inbox label before, how have you enabled that? It looks like the code that grabs the count is parsing that as `1120`.

**Comment by Thomas101** [comment]
I've not seen (11 : 20) unread count in the inbox label before, how have you enabled that? It looks like the code that grabs the count is parsing that as `1120`.

**Comment by amig** [comment]
Inbox settings:
![gmail-settings](https://cloud.githubusercontent.com/assets/203434/20132374/5675335c-a66b-11e6-8eea-abeaea9567ee.png)

**Comment by Thomas101** [comment]
Awesome! I know what's going wrong there. Thanks!

**Comment by Thomas101** [comment]
Opened pull request upstream (https://github.com/KartikTalwar/gmail.js/pull/326)

**Comment by Thomas101** [comment]
Hi this should be fixed in the latest [prerelease](thomas101.github.io/wmail/download?v=2.0.7). Thanks!

**Comment by amig** [comment]
Confirmed :D
